language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
  - npm install hexo-cli -g

script:
  - hexo generate

after_script:
  - cd public
  - git init
  - git config user.name "russellmars"
  - git config user.email "russellmars@sina.com"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${account}:${password}@${GH_REF}" master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/russellmars/russellmars.github.io.git