language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
 - npm install hexo-cli -g

install:
  - npm install

# before_script:
#   - npm install hexo-cli -g

script:
  - hexo generate

# before_deploy:
#   - cd public
#   - git init
#   - git config user.name "russellmars"
#   - git config user.email "russellmars@sina.com"
#   - git add .
#   - git commit -m "update blog"
  
deploy:
  local-dir: public
  email: russellmars@sina.com
  name: russellmars
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  target-branch: master
  on:
    branch: source

# after_script:
#   - cd public
#   - git init
#   - git config user.name "russellmars"
#   - git config user.email "russellmars@sina.com"
#   - git add .
#   - git commit -m "update blog"
  # - git push --force --quiet "https://${account}:${password}@${GH_REF}" master
# E: Build LifeCycle

# branches:
#   only:
#     - source
# env:
#  global:
#    - GH_REF: github.com/russellmars/russellmars.github.io.git